import { t } from "../../src/i18n";
import { Header } from "../partials/header";

export const Hero = () => (
  <div
    class={`
      m-(--hero-margin)
      flex
      h-[calc(100dvh-var(--banner-height)-var(--hero-margin-total))]
      flex-col
      overflow-hidden
      rounded-4xl
      bg-[url('/img/hero-background.webp')]
      bg-cover
      bg-center
      transition-all
      duration-300
      has-checked:m-0
      has-checked:rounded-none
      lg:has-checked:m-(--hero-margin)
      lg:has-checked:rounded-4xl
    `}
  >
    <Header />

    <section
      class={`
        flex
        flex-1
        flex-col
        items-center
        justify-center
        px-4
        pt-16
        pb-20
        text-center
        sm:px-6
        sm:pt-24
        sm:pb-32
        md:px-8
        md:pt-32
        md:pb-40
      `}
    >
      <div
        class={`
          hero-animate
          mb-6
          inline-flex
          items-center
          gap-1.5
          opacity-0
          sm:mb-8
          sm:gap-2
        `}
      >
        <img
          src="/img/hero-subtext-icon.svg"
          alt="Hero subtext icon"
          class={`
            h-6
            w-3
            sm:h-8
            sm:w-3
            md:h-10
            md:w-4
          `}
        />
        <span
          class={`
            text-xs
            font-medium
            text-foreground
            sm:text-sm
            md:text-base
          `}
        >
          {t("hero.badge")}
        </span>
        <img
          src="/img/hero-subtext-icon.svg"
          alt="Hero subtext icon"
          class={`
            h-6
            w-3
            -scale-x-100
            sm:h-8
            sm:w-3
            md:h-10
            md:w-4
          `}
        />
      </div>

      <h1
        class={`
          hero-animate
          max-w-5xl
          font-display
          text-3xl
          leading-[1.1]
          font-bold
          text-foreground
          opacity-0
          sm:text-4xl
          md:text-5xl
          lg:text-6xl
          xl:text-7xl
        `}
      >
        {t("hero.titleLine1")}
        <span
          class={`
            mt-1
            block
            sm:mt-2
          `}
        >
          {t("hero.titleLine2")}
        </span>
      </h1>

      <p
        class={`
          text-muted-foreground
          hero-animate
          mt-6
          max-w-2xl
          text-sm
          leading-relaxed
          font-normal
          opacity-0
          sm:mt-8
          sm:text-base
          md:text-lg
        `}
      >
        {t("hero.description")}
      </p>
    </section>

    <div
      class={`
        mx-4
        mb-4
        flex
        items-center
        justify-between
        sm:mb-6
      `}
    >
      <img
        src="/img/iso-badge.webp"
        alt="ISO 27001 Information Security Management"
        class={`
          h-8
          sm:h-10
        `}
      />
      <nav
        class={`
          flex
          items-center
          gap-4
          text-xs
          text-foreground
          sm:gap-6
          sm:text-sm
        `}
      >
        <a
          href="https://github.com/node101-io"
          class={`
            transition-colors
            hover:text-primary
          `}
          target="_blank"
        >
          GitHub
        </a>
        <a
          href="https://x.com/node_101"
          class={`
            transition-colors
            hover:text-primary
          `}
          target="_blank"
        >
          X
        </a>
      </nav>
    </div>
  </div>
);
